
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 21 14:49:14 ICT 2021
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TABLE_LITERAL = 41;
  public static final int DIVIDE = 5;
  public static final int LTE = 17;
  public static final int CHAR = 24;
  public static final int ADJ_LITERAL = 43;
  public static final int NOTEQUAL = 20;
  public static final int LPAREN = 11;
  public static final int SEMI = 10;
  public static final int INT = 21;
  public static final int MINUS = 3;
  public static final int PREPOSITION_LITERAL = 39;
  public static final int RPAREN = 12;
  public static final int AND = 13;
  public static final int ELSEIF = 31;
  public static final int LT = 15;
  public static final int OR = 14;
  public static final int all = 45;
  public static final int PLUS = 2;
  public static final int IF = 29;
  public static final int EXP = 34;
  public static final int ID = 37;
  public static final int DOT = 36;
  public static final int EOF = 0;
  public static final int BOOLEAN = 26;
  public static final int EQUAL = 19;
  public static final int NOUN_LITERAL = 40;
  public static final int error = 1;
  public static final int LCURLY = 27;
  public static final int the = 46;
  public static final int MOD = 6;
  public static final int EQ = 7;
  public static final int KIR = 22;
  public static final int GTE = 18;
  public static final int RCURLY = 28;
  public static final int TIMES = 4;
  public static final int of = 48;
  public static final int ELSE = 30;
  public static final int VERB_LITERAL = 38;
  public static final int WHILE = 32;
  public static final int LIST = 35;
  public static final int FLOAT = 23;
  public static final int details = 47;
  public static final int STRING = 25;
  public static final int DET_LITERAL = 44;
  public static final int GT = 16;
  public static final int NOPRINT = 8;
  public static final int ATTRIBUTE_LITERAL = 42;
  public static final int PRINT = 9;
  public static final int DO = 33;
}

